# Generated by Django 4.1.3 on 2024-03-28 01:33

import core.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feedback_email_alter_feedback_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(validators=[core.validations.validate_description]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, validators=[core.validations.validate_email]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(max_length=20, validators=[core.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(max_length=20, validators=[core.validations.validate_name]),
        ),
    ]
