# Generated by Django 4.1.3 on 2024-03-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'items'},
        ),
    ]
